name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Show eligible build destinations for Backtrace
      run: xcodebuild -showdestinations -scheme Backtrace
    - name: Build and test ( macOS 12.0 Monterey)
      run: xcodebuild test -scheme Backtrace-iOS-lib -destination 'platform=macOS,arch=x86_64,id=4666018E-420F-C1B5-9525-B145CECA79EB'
    - name: Build and test ( mac Catalyst 12.0)
      run: xcodebuild test -scheme Backtrace-macOS-lib -destination 'platform=macOS,arch=x86_64,variant=Mac Catalyst,id=4666018E-420F-C1B5-9525-B145CECA79EB'
    - name: Build and test ( tvOS 15.0)
      run: xcodebuild test -scheme Backtrace-tvOS-lib -destination 'platform=tvOS Simulator,OS=15.0,name=Apple TV 4K (2nd generation)'
    - name: Build and test ( iOS 15.0)
      run: xcodebuild test -scheme Backtrace-iOS-lib -destination 'platform=iOS Simulator,OS=15.0,name=iPhone 12 Pro'
