name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Show eligible build destinations for Backtrace iOS
      run: xcodebuild -showdestinations -scheme Backtrace-iOS-lib
    - name: Build and test ( iOS 15.0)
      run: xcodebuild test -scheme Backtrace-iOS-lib -destination 'platform=iOS Simulator, OS=15.2,name=iPhone 12 Pro'
